// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerstaOrderPrjoect.Data;

#nullable disable

namespace VerstaOrderPrjoect.Data.Migrations
{
    [DbContext(typeof(OrdersContext))]
    partial class OrdersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("VerstaOrderPrjoect.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressRecipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressSender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CityRecipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CitySender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PickupDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
